# Generated by Django 4.2.7 on 2026-04-04 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_original', models.TextField(verbose_name="Texte saisi par l'utilisateur")),
                ('type_operation', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat'), ('paiement', 'Paiement'), ('encaissement', 'Encaissement'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('impot', 'Impôt'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moyen_paiement', models.CharField(choices=[('caisse', 'Caisse (espèces)'), ('banque', 'Banque (virement)'), ('cheque', 'Chèque'), ('credit', 'Crédit (non payé)')], default='caisse', max_length=20)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('date_operation', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traitee_par_ia', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération',
                'ordering': ['-date_operation', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_debit', models.CharField(max_length=10, verbose_name='Compte Débit (PCM)')),
                ('libelle_debit', models.CharField(max_length=200, verbose_name='Libellé Débit')),
                ('compte_credit', models.CharField(max_length=10, verbose_name='Compte Crédit (PCM)')),
                ('libelle_credit', models.CharField(max_length=200, verbose_name='Libellé Crédit')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(max_length=300, verbose_name="Libellé de l'écriture")),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='operations.operation')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'ordering': ['-date_ecriture'],
            },
        ),
    ]
