import React, { createContext, useContext, useState } from 'react';

const T = {
  fr: {
    // Layout
    'nav.dashboard':    'Tableau de bord',
    'nav.saisie':       'Saisie IA',
    'nav.tresorerie':   'Trésorerie',
    'nav.resultat':     'Compte Résultat',
    'nav.bilan':        'Bilan',
    'nav.journal':      'Journal Comptable',
    'nav.correction':   'Correction IA',
    'nav.indicateurs':  'Indicateurs',
    'nav.deconnexion':  'Déconnexion',
    'nav.entreprise':   'Entreprise',

    // Common
    'common.loading':   'Chargement…',
    'common.year':      'Année',
    'common.month':     'Mois',
    'common.all_year':  "Toute l'année",
    'common.date':      'Date',
    'common.amount':    'Montant',
    'common.type':      'Type',
    'common.total':     'Total',
    'common.cancel':    'Annuler',
    'common.analyze':   'Analyser',
    'common.calculate': 'Calculer',
    'common.save':      'Enregistrer',
    'common.see_all':   'Voir tout →',
    'common.mru':       'MRU',
    'months': ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],

    // Auth
    'auth.login_tab':        'Connexion',
    'auth.register_tab':     'Inscription',
    'auth.email':            'Email',
    'auth.password':         'Mot de passe',
    'auth.company':          "Nom de l'entreprise",
    'auth.sector':           'Secteur d\'activité',
    'auth.submit_login':     'Se connecter',
    'auth.submit_register':  "S'inscrire",
    'auth.loading':          'Connexion…',
    'auth.registering':      'Inscription…',
    'auth.brand_title':      'Comptabilité Intelligente',
    'auth.brand_sub':        'pour la Mauritanie',
    'auth.feature_1':        'Saisie comptable par IA en langage naturel',
    'auth.feature_2':        'Plan Comptable BCM 1988 intégré',
    'auth.feature_3':        'Bilan, Résultat & Journal automatiques',
    'auth.feature_4':        'Correction de documents IA',
    'auth.feature_5':        'Indicateurs financiers avancés',
    'auth.right_title':      'Votre comptabilité,',
    'auth.right_sub':        'propulsée par l\'IA',
    'auth.right_desc':       'Gérez votre comptabilité en décrivant vos opérations en français. Notre IA génère les écritures comptables selon le PCM Mauritanien.',

    // Dashboard
    'dash.title':           'Tableau de bord',
    'dash.loading':         'Chargement du tableau de bord…',
    'dash.new_op':          'Nouvelle opération',
    'dash.sales_month':     'Ventes ce mois',
    'dash.expenses_month':  'Dépenses ce mois',
    'dash.net_result':      'Résultat net',
    'dash.total_ops':       'Total opérations',
    'dash.quick_access':    'Accès rapides',
    'dash.last_ops':        'Dernières opérations',
    'dash.no_ops':          'Aucune opération encore',
    'dash.no_ops_sub':      'Commencez à enregistrer vos transactions financières.',
    'dash.first_op':        'Première opération',
    'dash.description':     'Description',
    'dash.method':          'Moyen',
    'dash.type_vente':      'Vente',
    'dash.type_achat':      'Achat',
    'dash.type_paiement':   'Paiement',
    'dash.type_encaiss':    'Encaissement',
    'dash.type_salaire':    'Salaire',
    'dash.type_loyer':      'Loyer',
    'dash.type_impot':      'Impôt',
    'dash.type_autre':      'Autre',
    'dash.quick_treso':     'Trésorerie',
    'dash.quick_resultat':  'Compte Résultat',
    'dash.quick_bilan':     'Bilan',
    'dash.quick_correc':    'Correction IA',
    'dash.quick_indic':     'Indicateurs',

    // Saisie
    'saisie.title':         'Saisie intelligente',
    'saisie.subtitle':      "Décrivez votre opération en français — l'IA génère l'écriture comptable automatiquement.",
    'saisie.card_left':     "Décrire l'opération",
    'saisie.card_left_sub': 'En français, naturellement',
    'saisie.date_label':    "Date de l'opération",
    'saisie.text_label':    "Décrivez l'opération",
    'saisie.placeholder':   'Ex: Vendu 50 sacs de riz à 500 MRU en espèces au client…',
    'saisie.btn_loading':   'Analyse IA en cours…',
    'saisie.btn_submit':    'Analyser et enregistrer',
    'saisie.examples_title':'Exemples de saisie',
    'saisie.ai_card':       'Analyse IA',
    'saisie.ai_card_sub':   'Plan Comptable Mauritanien (BCM 1988)',
    'saisie.waiting':       "En attente d'analyse",
    'saisie.will_generate': "L'IA générera automatiquement :",
    'saisie.feat_entry':    'Écriture comptable D/C',
    'saisie.feat_treso':    'Mise à jour trésorerie',
    'saisie.feat_result':   'Compte de résultat',
    'saisie.feat_bilan':    'Bilan actualisé',
    'saisie.analyzing':     "L'IA analyse votre opération…",
    'saisie.pcm_note':      'Application du Plan Comptable BCM 1988',
    'saisie.success':       'Opération enregistrée avec succès',
    'saisie.entry_title':   'Écriture comptable',
    'saisie.new_op':        'Saisir une nouvelle opération',
    'saisie.summary_type':  'Type',
    'saisie.summary_amount':'Montant',
    'saisie.summary_method':'Moyen',
    'saisie.debit':         'DÉBIT',
    'saisie.credit':        'CRÉDIT',
    'saisie.error':         "Erreur lors de l'analyse IA.",

    // Tresorerie
    'treso.title':          'Trésorerie',
    'treso.subtitle':       'Vue mensuelle de vos flux de trésorerie',
    'treso.loading':        'Calcul de la trésorerie…',
    'treso.solde_caisse':   'Solde Caisse',
    'treso.solde_banque':   'Solde Banque',
    'treso.total':          'Total Trésorerie',
    'treso.encaissements':  'Encaissements',
    'treso.decaissements':  'Décaissements',
    'treso.chart_title':    'Recettes vs Dépenses',
    'treso.caisse_detail':  'Détail Caisse',
    'treso.banque_detail':  'Détail Banque',
    'treso.recettes':       'Recettes',
    'treso.depenses':       'Dépenses',
    'treso.ventes':         'Ventes encaissées',
    'treso.autres_enc':     'Autres encaissements',
    'treso.achats':         'Achats réglés',
    'treso.salaires':       'Salaires versés',
    'treso.loyers':         'Loyers payés',
    'treso.impots':         'Impôts payés',
    'treso.autres_dec':     'Autres décaissements',
    'treso.alert_caisse':   'Alerte : solde de caisse faible ou négatif',
    'treso.no_data':        'Aucune donnée pour cette période',

    // Journal
    'journal.title':        'Journal Comptable',
    'journal.subtitle':     'Toutes les écritures selon le Plan Comptable Mauritanien (PCM BCM 1988)',
    'journal.loading':      'Chargement des écritures…',
    'journal.total_debit':  'Total Débits',
    'journal.total_credit': 'Total Crédits',
    'journal.balanced':     'Équilibré — Débit = Crédit',
    'journal.no_entries':   'Aucune écriture comptable',
    'journal.no_entries_sub':'Les écritures apparaîtront ici après saisie des opérations.',
    'journal.col_date':     'Date',
    'journal.col_libelle':  'Libellé',
    'journal.col_debit_cpt':'Cpt. Débit',
    'journal.col_debit_lib':'Libellé Débit',
    'journal.col_credit_cpt':'Cpt. Crédit',
    'journal.col_credit_lib':'Libellé Crédit',
    'journal.col_amount':   'Montant',
    'journal.totaux':       'TOTAUX',
    'journal.ecriture':     'écriture',
    'journal.ecritures':    'écritures',
    'journal.legend_title': 'Classes du Plan Comptable Mauritanien (PCM BCM 1988)',
    'journal.legend_sub':   'Référence des numéros de comptes utilisés dans le journal',

    // Bilan
    'bilan.title':          'Bilan',
    'bilan.subtitle':       'Photo complète de votre situation financière',
    'bilan.loading':        'Calcul du bilan…',
    'bilan.period_at':      'Bilan au',
    'bilan.balanced':       'Équilibré',
    'bilan.unbalanced':     'Déséquilibré',
    'bilan.actif_title':    'ACTIF',
    'bilan.actif_sub':      'Ce que vous possédez · Classes 1 & 2 PCM',
    'bilan.passif_title':   'PASSIF',
    'bilan.passif_sub':     "D'où vient ce que vous possédez · Classes 3 & 5 PCM",
    'bilan.tresorerie':     'Trésorerie',
    'bilan.caisse':         'Caisse — Compte 100 (espèces)',
    'bilan.banque':         'Banque — Compte 12 (virements)',
    'bilan.sub_treso':      'Sous-total Trésorerie',
    'bilan.creances':       'Créances Clients',
    'bilan.clients':        'Clients — Compte 210 (ventes à crédit)',
    'bilan.capitaux':       'Capitaux Propres',
    'bilan.capital':        'Capital — Compte 59',
    'bilan.dettes':         'Dettes',
    'bilan.fournisseurs':   'Fournisseurs — Compte 320',
    'bilan.loyer_du':       'Loyer dû — Compte 320',
    'bilan.sub_dettes':     'Sous-total Dettes',
    'bilan.total_actif':    'TOTAL ACTIF',
    'bilan.total_passif':   'TOTAL PASSIF',
    'bilan.eq_ok':          'Bilan équilibré — Actif = Passif',
    'bilan.eq_nok':         'Bilan déséquilibré — Vérifiez vos opérations',
    'bilan.pcm_rule':       'Règle du PCM :',

    // Compte Résultat
    'result.title':         'Compte de Résultat',
    'result.subtitle':      'Gains vs Dépenses — Êtes-vous rentable ?',
    'result.loading':       'Calcul du compte de résultat…',
    'result.net_result':    'Résultat net de la période',
    'result.benefit':       'BÉNÉFICE',
    'result.loss':          'PERTE',
    'result.produits':      'Produits',
    'result.produits_sub':  'Classe 7 du Plan Comptable Mauritanien',
    'result.ventes':        'Ventes (Compte 702)',
    'result.encaissements': 'Encaissements divers (Compte 71)',
    'result.total_produits':'TOTAL PRODUITS',
    'result.charges':       'Charges',
    'result.charges_sub':   'Classe 6 du Plan Comptable Mauritanien',
    'result.achats':        'Achats marchandises (Compte 60)',
    'result.salaires':      'Salaires et charges (Compte 650)',
    'result.loyers':        'Loyers (Compte 620)',
    'result.impots':        'Impôts et taxes (Compte 66)',
    'result.autres':        'Autres paiements (Compte 63)',
    'result.total_charges': 'TOTAL CHARGES',
    'result.calc_title':    'Calcul du Résultat',
    'result.total_p7':      'Total Produits (Classe 7)',
    'result.total_c6':      'Total Charges (Classe 6)',
    'result.net_final':     'RÉSULTAT NET',

    // Correction
    'correc.title':         'Corrections IA',
    'correc.subtitle':      'Analysez vos documents comptables par image ou texte',
    'correc.loading':       "Analyse IA en cours…",
    'correc.tab_image':     'Image / Photo',
    'correc.tab_text':      'Texte',
    'correc.upload_hint':   'Glissez une image ou cliquez',
    'correc.upload_sub':    'PNG, JPG, PDF — max 10 MB',
    'correc.text_placeholder': 'Collez votre texte comptable ici…',
    'correc.btn_analyze':   'Analyser le document',
    'correc.ai_analyzing':  "L'IA analyse le document…",
    'correc.errors_found':  'erreur(s) détectée(s)',
    'correc.problem':       'Problème',
    'correc.correction':    'Correction',
    'correc.warnings':      'Avertissements',
    'correc.summary':       'Résumé',
    'correc.no_errors':     'Aucune erreur détectée',
    'correc.no_errors_sub': 'Le document semble correct selon le PCM.',
    'correc.change_image':  'Changer l\'image',

    // Financial Indicators
    'indic.title':          'Indicateurs Financiers',
    'indic.subtitle':       'Calculez vos KPIs financiers manuellement ou par IA',
    'indic.manual_tab':     'Calcul manuel',
    'indic.ai_tab':         'Analyse IA',
    'indic.bfr':            'Besoin en Fonds de Roulement (BFR)',
    'indic.van':            'Valeur Actuelle Nette (VAN)',
    'indic.ip':             'Indice de Profitabilité (IP)',
    'indic.drsi':           'Délai de Récupération SI (DRSI)',
    'indic.caf':            'Capacité d\'Autofinancement (CAF)',
    'indic.calculate':      'Calculer les indicateurs',
    'indic.ai_analyze':     'Analyser avec l\'IA',
    'indic.ai_analyzing':   'Analyse IA en cours…',
    'indic.results':        'Résultats',
    'indic.add_cashflow':   'Ajouter flux',
    'indic.cashflow_label': 'Flux de trésorerie annuels',
  },

  ar: {
    // Layout
    'nav.dashboard':    'لوحة التحكم',
    'nav.saisie':       'إدخال ذكي',
    'nav.tresorerie':   'الخزينة',
    'nav.resultat':     'حساب النتائج',
    'nav.bilan':        'الميزانية',
    'nav.journal':      'دفتر اليومية',
    'nav.correction':   'تصحيح ذكي',
    'nav.indicateurs':  'المؤشرات المالية',
    'nav.deconnexion':  'تسجيل الخروج',
    'nav.entreprise':   'شركة',

    // Common
    'common.loading':   'جاري التحميل…',
    'common.year':      'السنة',
    'common.month':     'الشهر',
    'common.all_year':  'كل السنة',
    'common.date':      'التاريخ',
    'common.amount':    'المبلغ',
    'common.type':      'النوع',
    'common.total':     'الإجمالي',
    'common.cancel':    'إلغاء',
    'common.analyze':   'تحليل',
    'common.calculate': 'حساب',
    'common.save':      'حفظ',
    'common.see_all':   '← عرض الكل',
    'common.mru':       'أوقية',
    'months': ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],

    // Auth
    'auth.login_tab':        'تسجيل الدخول',
    'auth.register_tab':     'إنشاء حساب',
    'auth.email':            'البريد الإلكتروني',
    'auth.password':         'كلمة المرور',
    'auth.company':          'اسم الشركة',
    'auth.sector':           'قطاع النشاط',
    'auth.submit_login':     'تسجيل الدخول',
    'auth.submit_register':  'إنشاء الحساب',
    'auth.loading':          'جاري الدخول…',
    'auth.registering':      'جاري التسجيل…',
    'auth.brand_title':      'محاسبة ذكية',
    'auth.brand_sub':        'لموريتانيا',
    'auth.feature_1':        'إدخال المحاسبة بالذكاء الاصطناعي بلغة طبيعية',
    'auth.feature_2':        'المخطط المحاسبي BCM 1988 مدمج',
    'auth.feature_3':        'الميزانية والنتائج واليومية تلقائية',
    'auth.feature_4':        'تصحيح الوثائق بالذكاء الاصطناعي',
    'auth.feature_5':        'مؤشرات مالية متقدمة',
    'auth.right_title':      'محاسبتك،',
    'auth.right_sub':        'مدعومة بالذكاء الاصطناعي',
    'auth.right_desc':       'أدر محاسبتك بوصف عملياتك بالفرنسية. يولّد الذكاء الاصطناعي القيود المحاسبية وفق المخطط الموريتاني.',

    // Dashboard
    'dash.title':           'لوحة التحكم',
    'dash.loading':         'جاري تحميل لوحة التحكم…',
    'dash.new_op':          'عملية جديدة',
    'dash.sales_month':     'مبيعات هذا الشهر',
    'dash.expenses_month':  'مصروفات هذا الشهر',
    'dash.net_result':      'النتيجة الصافية',
    'dash.total_ops':       'إجمالي العمليات',
    'dash.quick_access':    'وصول سريع',
    'dash.last_ops':        'آخر العمليات',
    'dash.no_ops':          'لا توجد عمليات بعد',
    'dash.no_ops_sub':      'ابدأ بتسجيل معاملاتك المالية.',
    'dash.first_op':        'العملية الأولى',
    'dash.description':     'الوصف',
    'dash.method':          'وسيلة الدفع',
    'dash.type_vente':      'بيع',
    'dash.type_achat':      'شراء',
    'dash.type_paiement':   'دفع',
    'dash.type_encaiss':    'تحصيل',
    'dash.type_salaire':    'راتب',
    'dash.type_loyer':      'إيجار',
    'dash.type_impot':      'ضريبة',
    'dash.type_autre':      'أخرى',
    'dash.quick_treso':     'الخزينة',
    'dash.quick_resultat':  'حساب النتائج',
    'dash.quick_bilan':     'الميزانية',
    'dash.quick_correc':    'تصحيح ذكي',
    'dash.quick_indic':     'المؤشرات',

    // Saisie
    'saisie.title':         'إدخال ذكي',
    'saisie.subtitle':      'صف عمليتك بالفرنسية — يولّد الذكاء الاصطناعي القيد المحاسبي تلقائياً.',
    'saisie.card_left':     'وصف العملية',
    'saisie.card_left_sub': 'بالفرنسية (مطلوب للذكاء الاصطناعي)',
    'saisie.date_label':    'تاريخ العملية',
    'saisie.text_label':    'صف العملية',
    'saisie.placeholder':   'مثال: Vendu 50 sacs de riz à 500 MRU en espèces…',
    'saisie.btn_loading':   'جاري التحليل…',
    'saisie.btn_submit':    'تحليل وتسجيل',
    'saisie.examples_title':'أمثلة للإدخال',
    'saisie.ai_card':       'تحليل الذكاء الاصطناعي',
    'saisie.ai_card_sub':   'المخطط المحاسبي الموريتاني (BCM 1988)',
    'saisie.waiting':       'في انتظار التحليل',
    'saisie.will_generate': 'سيولّد الذكاء الاصطناعي تلقائياً:',
    'saisie.feat_entry':    'قيد محاسبي مدين/دائن',
    'saisie.feat_treso':    'تحديث الخزينة',
    'saisie.feat_result':   'حساب النتائج',
    'saisie.feat_bilan':    'تحديث الميزانية',
    'saisie.analyzing':     'الذكاء الاصطناعي يحلل عمليتك…',
    'saisie.pcm_note':      'تطبيق المخطط المحاسبي BCM 1988',
    'saisie.success':       'تم تسجيل العملية بنجاح',
    'saisie.entry_title':   'القيد المحاسبي',
    'saisie.new_op':        'إدخال عملية جديدة',
    'saisie.summary_type':  'النوع',
    'saisie.summary_amount':'المبلغ',
    'saisie.summary_method':'الوسيلة',
    'saisie.debit':         'مدين',
    'saisie.credit':        'دائن',
    'saisie.error':         'خطأ في تحليل الذكاء الاصطناعي.',

    // Tresorerie
    'treso.title':          'الخزينة',
    'treso.subtitle':       'عرض شهري لتدفقاتك النقدية',
    'treso.loading':        'جاري حساب الخزينة…',
    'treso.solde_caisse':   'رصيد الصندوق',
    'treso.solde_banque':   'رصيد البنك',
    'treso.total':          'إجمالي الخزينة',
    'treso.encaissements':  'التحصيلات',
    'treso.decaissements':  'المصروفات',
    'treso.chart_title':    'الإيرادات مقابل المصروفات',
    'treso.caisse_detail':  'تفاصيل الصندوق',
    'treso.banque_detail':  'تفاصيل البنك',
    'treso.recettes':       'الإيرادات',
    'treso.depenses':       'المصروفات',
    'treso.ventes':         'مبيعات محصّلة',
    'treso.autres_enc':     'تحصيلات أخرى',
    'treso.achats':         'مشتريات مدفوعة',
    'treso.salaires':       'رواتب مدفوعة',
    'treso.loyers':         'إيجارات مدفوعة',
    'treso.impots':         'ضرائب مدفوعة',
    'treso.autres_dec':     'مصروفات أخرى',
    'treso.alert_caisse':   'تنبيه: رصيد الصندوق منخفض أو سالب',
    'treso.no_data':        'لا توجد بيانات لهذه الفترة',

    // Journal
    'journal.title':        'دفتر اليومية',
    'journal.subtitle':     'جميع القيود وفق المخطط المحاسبي الموريتاني (PCM BCM 1988)',
    'journal.loading':      'جاري تحميل القيود…',
    'journal.total_debit':  'إجمالي المدينين',
    'journal.total_credit': 'إجمالي الدائنين',
    'journal.balanced':     'متوازن — المدين = الدائن',
    'journal.no_entries':   'لا توجد قيود محاسبية',
    'journal.no_entries_sub':'ستظهر القيود هنا بعد إدخال العمليات.',
    'journal.col_date':     'التاريخ',
    'journal.col_libelle':  'البيان',
    'journal.col_debit_cpt':'ح. المدين',
    'journal.col_debit_lib':'بيان المدين',
    'journal.col_credit_cpt':'ح. الدائن',
    'journal.col_credit_lib':'بيان الدائن',
    'journal.col_amount':   'المبلغ',
    'journal.totaux':       'الإجماليات',
    'journal.ecriture':     'قيد',
    'journal.ecritures':    'قيود',
    'journal.legend_title': 'أصناف المخطط المحاسبي الموريتاني (PCM BCM 1988)',
    'journal.legend_sub':   'مرجع أرقام الحسابات المستخدمة في دفتر اليومية',

    // Bilan
    'bilan.title':          'الميزانية',
    'bilan.subtitle':       'صورة كاملة لوضعك المالي',
    'bilan.loading':        'جاري حساب الميزانية…',
    'bilan.period_at':      'الميزانية في',
    'bilan.balanced':       'متوازنة',
    'bilan.unbalanced':     'غير متوازنة',
    'bilan.actif_title':    'الأصول',
    'bilan.actif_sub':      'ما تملكه · الصنفان 1 و 2',
    'bilan.passif_title':   'الخصوم',
    'bilan.passif_sub':     'مصادر ما تملكه · الصنفان 3 و 5',
    'bilan.tresorerie':     'الخزينة',
    'bilan.caisse':         'الصندوق — حساب 100 (نقد)',
    'bilan.banque':         'البنك — حساب 12 (تحويلات)',
    'bilan.sub_treso':      'مجموع الخزينة',
    'bilan.creances':       'مستحقات العملاء',
    'bilan.clients':        'العملاء — حساب 210 (مبيعات بالأجل)',
    'bilan.capitaux':       'حقوق الملكية',
    'bilan.capital':        'رأس المال — حساب 59',
    'bilan.dettes':         'الديون',
    'bilan.fournisseurs':   'الموردون — حساب 320',
    'bilan.loyer_du':       'إيجار مستحق — حساب 320',
    'bilan.sub_dettes':     'مجموع الديون',
    'bilan.total_actif':    'إجمالي الأصول',
    'bilan.total_passif':   'إجمالي الخصوم',
    'bilan.eq_ok':          'الميزانية متوازنة — الأصول = الخصوم',
    'bilan.eq_nok':         'الميزانية غير متوازنة — راجع عملياتك',
    'bilan.pcm_rule':       'قاعدة المخطط المحاسبي:',

    // Compte Résultat
    'result.title':         'حساب النتائج',
    'result.subtitle':      'الإيرادات مقابل المصروفات — هل أنت مربح؟',
    'result.loading':       'جاري حساب النتائج…',
    'result.net_result':    'صافي نتيجة الفترة',
    'result.benefit':       'ربح',
    'result.loss':          'خسارة',
    'result.produits':      'الإيرادات',
    'result.produits_sub':  'الصنف 7 من المخطط المحاسبي الموريتاني',
    'result.ventes':        'المبيعات (حساب 702)',
    'result.encaissements': 'تحصيلات متنوعة (حساب 71)',
    'result.total_produits':'إجمالي الإيرادات',
    'result.charges':       'المصروفات',
    'result.charges_sub':   'الصنف 6 من المخطط المحاسبي الموريتاني',
    'result.achats':        'مشتريات البضائع (حساب 60)',
    'result.salaires':      'الرواتب والأعباء (حساب 650)',
    'result.loyers':        'الإيجارات (حساب 620)',
    'result.impots':        'الضرائب والرسوم (حساب 66)',
    'result.autres':        'مدفوعات أخرى (حساب 63)',
    'result.total_charges': 'إجمالي المصروفات',
    'result.calc_title':    'حساب النتيجة',
    'result.total_p7':      'إجمالي الإيرادات (الصنف 7)',
    'result.total_c6':      'إجمالي المصروفات (الصنف 6)',
    'result.net_final':     'النتيجة الصافية',

    // Correction
    'correc.title':         'تصحيح ذكي',
    'correc.subtitle':      'حلّل وثائقك المحاسبية بالصورة أو النص',
    'correc.loading':       'جاري التحليل بالذكاء الاصطناعي…',
    'correc.tab_image':     'صورة / صورة فوتوغرافية',
    'correc.tab_text':      'نص',
    'correc.upload_hint':   'اسحب صورة أو انقر للاختيار',
    'correc.upload_sub':    'PNG، JPG، PDF — الحد الأقصى 10 ميغابايت',
    'correc.text_placeholder': 'الصق نصك المحاسبي هنا…',
    'correc.btn_analyze':   'تحليل الوثيقة',
    'correc.ai_analyzing':  'الذكاء الاصطناعي يحلل الوثيقة…',
    'correc.errors_found':  'خطأ/أخطاء مكتشفة',
    'correc.problem':       'المشكلة',
    'correc.correction':    'التصحيح',
    'correc.warnings':      'تحذيرات',
    'correc.summary':       'الملخص',
    'correc.no_errors':     'لم يتم اكتشاف أي أخطاء',
    'correc.no_errors_sub': 'يبدو أن الوثيقة صحيحة وفق المخطط المحاسبي.',
    'correc.change_image':  'تغيير الصورة',

    // Financial Indicators
    'indic.title':          'المؤشرات المالية',
    'indic.subtitle':       'احسب مؤشراتك المالية يدوياً أو بالذكاء الاصطناعي',
    'indic.manual_tab':     'حساب يدوي',
    'indic.ai_tab':         'تحليل ذكي',
    'indic.bfr':            'احتياجات رأس المال العامل (BFR)',
    'indic.van':            'صافي القيمة الحالية (VAN)',
    'indic.ip':             'مؤشر الربحية (IP)',
    'indic.drsi':           'فترة الاسترداد (DRSI)',
    'indic.caf':            'طاقة التمويل الذاتي (CAF)',
    'indic.calculate':      'حساب المؤشرات',
    'indic.ai_analyze':     'تحليل بالذكاء الاصطناعي',
    'indic.ai_analyzing':   'جاري التحليل بالذكاء الاصطناعي…',
    'indic.results':        'النتائج',
    'indic.add_cashflow':   'إضافة تدفق',
    'indic.cashflow_label': 'التدفقات النقدية السنوية',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'fr');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
  };

  const t = (key) => T[lang]?.[key] ?? T['fr']?.[key] ?? key;
  const months = T[lang]?.['months'] || T['fr']['months'];
  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLang, t, months, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
